# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Josiah Davis
tagline:          Mad Data Scientist
description:      'Challenging conventional wisdom. Committed to curiosity. Made by <a href="https://twitter.com/josiahjdavis" target="_blank">@josiahjdavis</a>.'
url:              josiahjdavis.com

author:
  name:           'Josiah Davis'
  url:            https://twitter.com/josiahjdavis

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
