---
layout: post
title: Why do artists starve?
---

It is a well known fact among artists, that unless you make it to the very top of your field, you generally are not going to be making a lot of money. According to the [Bureau of Labor Statistics](http://www.bls.gov/oes/current/naics4_711100.htm) the median hourly wage for performing artists is less than $30. This might sound like a decent hourly rate, except when you consider that many artists are only paid for performances and limited rehearsals (if any) and that many artists live in cities like New York, San Francisco, and Chicago, where the cost of living is considerably higher than average. All that to say, choosing to go into the arts in order to make money is a little bit like choosing to go onto [The Bachelor](http://www.huffingtonpost.com/2013/08/12/bachelor-couples_n_3728241.html) to find your one true love. It's not that it's impossible, but it it sure isn't likely. What is it about the arts scene in America that leads artists to struggle to make ends meat?

### Big brother, where art thou?
One answer is to blame the government. After all, direct public funding for the arts in the U.S. pales in comparison to other developed countries. This is true even after taking into consideration the fact that European governments tend to collect more tax revenue per citizen than the U.S. According to [data](http://arts.gov/sites/default/files/74.pdf) published by the Arts Council of England, 1.79% of Germany’s total public expenditure (including spending at the federal, municipal, and local level) goes directly to support the arts. That might not sound like a lot. However it's nearly 14 times the 0.13% that the U.S. spends. This data was published in 1998 and is admittedly out of date, however, there is reason to believe that the difference has only increased in recent years. Since the establishment of the National Endowment for the Arts in 1986, total US funding for the arts has [decreased by 31%](http://www.giarts.org/article/public-funding-arts-2014-update) after adjusting for inflation. In contrast, funding in Germany appears to be going in [the opposite direction](http://www.lejournaldesarts.fr/site/archives/docs_article/105729/le-budget-de-la-culture-augmentera-de-8--en-allemagne-en-2013.php). And this unfavorable comparison isn't limited to Germany. When compared to other european countries, U.S. Funding for the arts is extremely low for 1st world country standards.

### Art Attack
Another answer is to blame the artist. This is the main idea set forth by Hans Abbing in his book: Why are Artists Poor? The Exceptional Economy of the Arts. Here is how he explains it: Artists generally favor creative freedom and autonomy over commerce and profitability, and this dynamic has a negative reinforcing effect on the economy of the arts. Whenever an artist offers their craft for free, it has the effect of cannibalizing the would-be businesses of their fellow artists. According to this theory, the solution is for artists to band together, demand fair pay, and generally avoid offering their work for free. Indeed, [Working Artists and the Greater Economy (W.A.G.E)](http://www.wageforwork.com/about/1/womanifesto), is a activist labor organization for artists that has attempted to do just this. Among other things, they provide a certification that non-profits can earn only if they meet certain [standards](http://www.wageforwork.com/certification/3/how-to-get-certified) for how they pay their artists.

### The Fundamental Issue: Lack of interest
While both of these answers have merit, there is another more basic answer: there just isn't that much interest. According to this theory, America doesn't have the appreciation for the arts that it does for say, Lebron James, Tom Cruise and Kim Kardashian. There is good data in support of this idea. According to GSS surveys only 25% of the general public paid to attend an artistic performance in the last 12 months.  Compare this to 50% of people who attended a sporting event and 75% who attended a movie in the prior 12 months (both of which are typically paid events). And it gets worse. The chart below displays a comparison of 8 motivations for attending an art performance. Here are three observations:

  * People go to performances, not primarily to enjoy the art itself, but to hangout with people. Regardless of gender, income, race, ethnicity, or generation, Socializing with Family and Friends was consistently the first or second most common motivation. There are two ways of viewing this. It's great that the arts have the ability to bring people together. However, if this is the primary reason that we attend artistic performances, you have to wonder, are we missing out something better and richer?

  * Americans do not have a strong tradition of supporting the arts and viewing the arts as a vital part of their local communities. Of all of the people who attended performances, only 1 out of 4 people did so to support their communities, and only 1 out of 10 attended performances as a means of celebrating their cultural heritage. As Americans, we are probably more likely to feel heritage with things like summer blockbusters, college football, and cheap, reality TV.

  * There is a lack of appreciation for high quality art. Only slightly above one in three people cited Experiencing High Quality Art as a major motivation, and that may be a high estimate. For comparison, approximately one out of three people also cited the location of the performance as a major motivation for their attendance. Here is what this means: for many people, good art is only worthwhile insofar as it is convenient.

If all this sounds rather dismal, it is. However, a closer look at the data reveals a silver lining. The second most common reason generally cited was to see a specific performer. Now, this might mean the specific performer was a some celebrity pop star appearing in an otherwise unremarkable performance, like, for example, Jonah Hill starring in the Broadway musical, "How to succeed in business". Alternatively, this could mean that there was a some personal connection between the attendee and someone in the performance. While the split between these two different cases is unclear, one thing is certain: in many cases, the best person to get you excited about something is another person who is already excited about it. And who is more engaged with and knowledgable about art than an artist? After all, they aren't starving from a lack of passion.
